version: '3'

services:
  poker_analize:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/poker_analize/node_modules
    ports:
      - "3000:3000"