export type PokerSituation = {
    heroPosition: Position
    villainPosition: Position
    raiseCount: number
    firstRaiser: Player
}

export type Position = "utg" | "hj" | "co" | "btn" | "sb" | "bb" | ""
export type Player = "hero" | "villain"
export type Action = {
    raises: number
    calls: number
    folds: number
}
export type CardList = {
    AA:Action
    KK:Action
    QQ:Action
    JJ:Action
    TT:Action
    99:Action
    88:Action
    77:Action
    66:Action
    55:Action
    44:Action
    33:Action
    22:Action
    AKs:Action
    AQs:Action
    AJs:Action
    ATs:Action
    A9s:Action
    A8s:Action
    A7s:Action
    A6s:Action
    A5s:Action
    A4s:Action
    A3s:Action
    A2s:Action
    KQs:Action
    KJs:Action
    KTs:Action
    K9s:Action
    K8s:Action
    K7s:Action
    K6s:Action
    K5s:Action
    K4s:Action
    K3s:Action
    K2s:Action
    QJs:Action
    QTs:Action
    Q9s:Action
    Q8s:Action
    Q7s:Action
    Q6s:Action
    Q5s:Action
    Q4s:Action
    Q3s:Action
    Q2s:Action
    JTs:Action
    J9s:Action
    J8s:Action
    J7s:Action
    J6s:Action
    J5s:Action
    J4s:Action
    J3s:Action
    J2s:Action
    T9s:Action
    T8s:Action
    T7s:Action
    T6s:Action
    T5s:Action
    T4s:Action
    T3s:Action
    T2s:Action
    "98s":Action
    "97s":Action
    "96s":Action
    "95s":Action
    "94s":Action
    "93s":Action
    "92s":Action
    "87s":Action
    "86s":Action
    "85s":Action
    "84s":Action
    "83s":Action
    "82s":Action
    "76s":Action
    "75s":Action
    "74s":Action
    "73s":Action
    "72s":Action
    "65s":Action
    "64s":Action
    "63s":Action
    "62s":Action
    "54s":Action
    "53s":Action
    "52s":Action
    "43s":Action
    "42s":Action
    "32s":Action
    AKo:Action
    AQo:Action
    AJo:Action
    ATo:Action
    A9o:Action
    A8o:Action
    A7o:Action
    A6o:Action
    A5o:Action
    A4o:Action
    A3o:Action
    A2o:Action
    KQo:Action
    KJo:Action
    KTo:Action
    K9o:Action
    K8o:Action
    K7o:Action
    K6o:Action
    K5o:Action
    K4o:Action
    K3o:Action
    K2o:Action
    QJo:Action
    QTo:Action
    Q9o:Action
    Q8o:Action
    Q7o:Action
    Q6o:Action
    Q5o:Action
    Q4o:Action
    Q3o:Action
    Q2o:Action
    JTo:Action
    J9o:Action
    J8o:Action
    J7o:Action
    J6o:Action
    J5o:Action
    J4o:Action
    J3o:Action
    J2o:Action
    T9o:Action
    T8o:Action
    T7o:Action
    T6o:Action
    T5o:Action
    T4o:Action
    T3o:Action
    T2o:Action
    "98o":Action
    "97o":Action
    "96o":Action
    "95o":Action
    "94o":Action
    "93o":Action
    "92o":Action
    "87o":Action
    "86o":Action
    "85o":Action
    "84o":Action
    "83o":Action
    "82o":Action
    "76o":Action
    "75o":Action
    "74o":Action
    "73o":Action
    "72o":Action
    "65o":Action
    "64o":Action
    "63o":Action
    "62o":Action
    "54o":Action
    "53o":Action
    "52o":Action
    "43o":Action
    "42o":Action
    "32o":Action
    
    
}